In [82]:
import pandas as pd
from utility import select_df
from utility_WHO import select_df
import numpy as np
# reload automatically from the imported scripts
%load_ext autoreload
%autoreload 2
raw_df = pd.read_csv("/Users/wei/mph_dissertation/test_file/Smoking Prevalence/Prevalence_of_current_tobacco_use_between_Males_and_Females.csv")
raw_df1 = pd.read_csv("/Users/wei/mph_dissertation/test_file/WHO Cardiovascular Mortality Database/WHO Cardiovascular Disease Mortality Database_1st Dec 2022.csv")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [83]:
column_drop = ['Code', 'Continent']
na_header =['Prevalence of current tobacco use, males (% of male adults)', 
            'Prevalence of current tobacco use, females (% of female adults)']
Tobacco_use_in_WHO_MEMBER_STATES=select_df(raw_df, column_drop=column_drop, drop_na=na_header)
Tobacco_use_in_WHO_MEMBER_STATES

,Entity,Year,"Prevalence of current tobacco use, males (% of male adults)","Prevalence of current tobacco use, females (% of female adults)",Population (historical estimates)
1,Afghanistan,2005,50.799999,14.5,24411196.0
2,Afghanistan,2010,46.799999,11.4,28189672.0
3,Afghanistan,2015,42.900002,9.1,33753500.0
4,Afghanistan,2018,40.799999,7.9,36686788.0
5,Afghanistan,2019,40.099998,7.5,37769496.0
...,...,...,...,...,...
5346,Zimbabwe,2010,28.600000,2.6,12839774.0
5347,Zimbabwe,2015,25.100000,2.0,14154937.0
5348,Zimbabwe,2018,23.000000,1.7,15052191.0
5349,Zimbabwe,2019,22.500000,1.6,15354606.0
5350,Zimbabwe,2020,21.799999,1.5,15669663.0

In [114]:
column_drop = ['Country Code','Region Name', 'Region Code','Age-standardized death rate per 100 000 standard population','Unnamed: 12']
na_header =['Number', 
            'Percentage of cause-specific deaths out of total deaths',
            'Death rate per 100 000 population'
           ]
df1=select_df(raw_df1, column_drop=column_drop, drop_na=na_header)
WHO_Cardiovascular_Disease_Mortality=df1.rename(columns={'Country Name':'Entity'})
df=WHO_Cardiovascular_Disease_Mortality

In [80]:
#frames = [Tobacco_use_in_WHO_MEMBER_STATES, WHO_Cardiovascular_Disease_Mortality]
#merge_result = pd.concat(frames)
#merge_result

In [33]:
#merge Tobacco_use_in_WHO_MEMBER_STATES,WHO_Cardiovascular_Disease_Mortality : "Entity" and "Year"

In [34]:
#tab1=pd.merge(Tobacco_use_in_WHO_MEMBER_STATES,WHO_Cardiovascular_Disease_Mortality, on=["Entity","Entity"])
#tab2=pd.merge(Tobacco_use_in_WHO_MEMBER_STATES,WHO_Cardiovascular_Disease_Mortality, on=["Year","Year"])
#tab3=pd.merge(tab1, tab2)
#tab3 
#filt=(WHO_Cardiovascular_Disease_Mortality['Year']=='2000')
#WHO_Cardiovascular_Disease_Mortality.loc[filt]

In [ ]:
#如果 WHO 的"Year" 在Tobacoo Use "Year" 裡，那就取出來 再創造一個df

In [121]:
condition=df["Year"]==2005 #OurWorldData 的年份只從2000年開始
df=df[condition]